// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/model/drawing.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ImageData) Reset() {
	*x = ImageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageData) ProtoMessage() {}

func (x *ImageData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageData.ProtoReflect.Descriptor instead.
func (*ImageData) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{0}
}

func (x *ImageData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventDrawingUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata  *EventMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ImageData *ImageData     `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
}

func (x *EventDrawingUpdate) Reset() {
	*x = EventDrawingUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventDrawingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDrawingUpdate) ProtoMessage() {}

func (x *EventDrawingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDrawingUpdate.ProtoReflect.Descriptor instead.
func (*EventDrawingUpdate) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{1}
}

func (x *EventDrawingUpdate) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EventDrawingUpdate) GetImageData() *ImageData {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type EventDrawingDetectQueue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *EventMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	BoardId  *UUID          `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
}

func (x *EventDrawingDetectQueue) Reset() {
	*x = EventDrawingDetectQueue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventDrawingDetectQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDrawingDetectQueue) ProtoMessage() {}

func (x *EventDrawingDetectQueue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDrawingDetectQueue.ProtoReflect.Descriptor instead.
func (*EventDrawingDetectQueue) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{2}
}

func (x *EventDrawingDetectQueue) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EventDrawingDetectQueue) GetBoardId() *UUID {
	if x != nil {
		return x.BoardId
	}
	return nil
}

type EventDrawingDetect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata    *EventMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Description string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *EventDrawingDetect) Reset() {
	*x = EventDrawingDetect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventDrawingDetect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDrawingDetect) ProtoMessage() {}

func (x *EventDrawingDetect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDrawingDetect.ProtoReflect.Descriptor instead.
func (*EventDrawingDetect) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{3}
}

func (x *EventDrawingDetect) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EventDrawingDetect) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateDrawingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoardId   *UUID      `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	ImageData *ImageData `protobuf:"bytes,3,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
}

func (x *UpdateDrawingRequest) Reset() {
	*x = UpdateDrawingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDrawingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDrawingRequest) ProtoMessage() {}

func (x *UpdateDrawingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDrawingRequest.ProtoReflect.Descriptor instead.
func (*UpdateDrawingRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDrawingRequest) GetBoardId() *UUID {
	if x != nil {
		return x.BoardId
	}
	return nil
}

func (x *UpdateDrawingRequest) GetImageData() *ImageData {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type UpdateDrawingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateDrawingResponse) Reset() {
	*x = UpdateDrawingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDrawingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDrawingResponse) ProtoMessage() {}

func (x *UpdateDrawingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDrawingResponse.ProtoReflect.Descriptor instead.
func (*UpdateDrawingResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDrawingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetBoardDrawingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoardId *UUID `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
}

func (x *GetBoardDrawingsRequest) Reset() {
	*x = GetBoardDrawingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBoardDrawingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardDrawingsRequest) ProtoMessage() {}

func (x *GetBoardDrawingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardDrawingsRequest.ProtoReflect.Descriptor instead.
func (*GetBoardDrawingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{6}
}

func (x *GetBoardDrawingsRequest) GetBoardId() *UUID {
	if x != nil {
		return x.BoardId
	}
	return nil
}

type GetBoardDrawingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// map<userUUID, ImageData>
	Drawings map[string]*ImageData `protobuf:"bytes,1,rep,name=drawings,proto3" json:"drawings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetBoardDrawingsResponse) Reset() {
	*x = GetBoardDrawingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBoardDrawingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardDrawingsResponse) ProtoMessage() {}

func (x *GetBoardDrawingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardDrawingsResponse.ProtoReflect.Descriptor instead.
func (*GetBoardDrawingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{7}
}

func (x *GetBoardDrawingsResponse) GetDrawings() map[string]*ImageData {
	if x != nil {
		return x.Drawings
	}
	return nil
}

type DrawingDetectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DrawingDetectResponse) Reset() {
	*x = DrawingDetectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_drawing_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawingDetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawingDetectResponse) ProtoMessage() {}

func (x *DrawingDetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_drawing_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawingDetectResponse.ProtoReflect.Descriptor instead.
func (*DrawingDetectResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_drawing_proto_rawDescGZIP(), []int{8}
}

func (x *DrawingDetectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_model_drawing_proto protoreflect.FileDescriptor

var file_proto_model_drawing_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x64, 0x72,
	0x61, 0x77, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x09,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x77, 0x0a,
	0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x73, 0x0a, 0x17, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44,
	0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x08, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x55,
	0x49, 0x44, 0x52, 0x07, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x12, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6f, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x08, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x07, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x61, 0x72, 0x64, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55,
	0x55, 0x49, 0x44, 0x52, 0x07, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0xb4, 0x01, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x08, 0x64, 0x72, 0x61,
	0x77, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x44, 0x72, 0x61, 0x77,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x72, 0x61,
	0x77, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x64, 0x72, 0x61, 0x77,
	0x69, 0x6e, 0x67, 0x73, 0x1a, 0x4d, 0x0a, 0x0d, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x31, 0x0a, 0x15, 0x44, 0x72, 0x61, 0x77, 0x69, 0x6e, 0x67, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6e, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6e, 0x2f, 0x64,
	0x72, 0x61, 0x77, 0x2d, 0x74, 0x6f, 0x67, 0x65, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_model_drawing_proto_rawDescOnce sync.Once
	file_proto_model_drawing_proto_rawDescData = file_proto_model_drawing_proto_rawDesc
)

func file_proto_model_drawing_proto_rawDescGZIP() []byte {
	file_proto_model_drawing_proto_rawDescOnce.Do(func() {
		file_proto_model_drawing_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_drawing_proto_rawDescData)
	})
	return file_proto_model_drawing_proto_rawDescData
}

var file_proto_model_drawing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_model_drawing_proto_goTypes = []interface{}{
	(*ImageData)(nil),                // 0: model.ImageData
	(*EventDrawingUpdate)(nil),       // 1: model.EventDrawingUpdate
	(*EventDrawingDetectQueue)(nil),  // 2: model.EventDrawingDetectQueue
	(*EventDrawingDetect)(nil),       // 3: model.EventDrawingDetect
	(*UpdateDrawingRequest)(nil),     // 4: model.UpdateDrawingRequest
	(*UpdateDrawingResponse)(nil),    // 5: model.UpdateDrawingResponse
	(*GetBoardDrawingsRequest)(nil),  // 6: model.GetBoardDrawingsRequest
	(*GetBoardDrawingsResponse)(nil), // 7: model.GetBoardDrawingsResponse
	(*DrawingDetectResponse)(nil),    // 8: model.DrawingDetectResponse
	nil,                              // 9: model.GetBoardDrawingsResponse.DrawingsEntry
	(*EventMetadata)(nil),            // 10: model.EventMetadata
	(*UUID)(nil),                     // 11: model.UUID
}
var file_proto_model_drawing_proto_depIdxs = []int32{
	10, // 0: model.EventDrawingUpdate.metadata:type_name -> model.EventMetadata
	0,  // 1: model.EventDrawingUpdate.image_data:type_name -> model.ImageData
	10, // 2: model.EventDrawingDetectQueue.metadata:type_name -> model.EventMetadata
	11, // 3: model.EventDrawingDetectQueue.board_id:type_name -> model.UUID
	10, // 4: model.EventDrawingDetect.metadata:type_name -> model.EventMetadata
	11, // 5: model.UpdateDrawingRequest.board_id:type_name -> model.UUID
	0,  // 6: model.UpdateDrawingRequest.image_data:type_name -> model.ImageData
	11, // 7: model.GetBoardDrawingsRequest.board_id:type_name -> model.UUID
	9,  // 8: model.GetBoardDrawingsResponse.drawings:type_name -> model.GetBoardDrawingsResponse.DrawingsEntry
	0,  // 9: model.GetBoardDrawingsResponse.DrawingsEntry.value:type_name -> model.ImageData
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_model_drawing_proto_init() }
func file_proto_model_drawing_proto_init() {
	if File_proto_model_drawing_proto != nil {
		return
	}
	file_proto_model_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_model_drawing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_drawing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventDrawingUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_drawing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventDrawingDetectQueue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_drawing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventDrawingDetect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_drawing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDrawingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_drawing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDrawingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_drawing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBoardDrawingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_drawing_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBoardDrawingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_drawing_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrawingDetectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_drawing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_drawing_proto_goTypes,
		DependencyIndexes: file_proto_model_drawing_proto_depIdxs,
		MessageInfos:      file_proto_model_drawing_proto_msgTypes,
	}.Build()
	File_proto_model_drawing_proto = out.File
	file_proto_model_drawing_proto_rawDesc = nil
	file_proto_model_drawing_proto_goTypes = nil
	file_proto_model_drawing_proto_depIdxs = nil
}
