// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: proto/model/pointer.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PointerPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *PointerPosition) Reset() {
	*x = PointerPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_pointer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointerPosition) ProtoMessage() {}

func (x *PointerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_pointer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointerPosition.ProtoReflect.Descriptor instead.
func (*PointerPosition) Descriptor() ([]byte, []int) {
	return file_proto_model_pointer_proto_rawDescGZIP(), []int{0}
}

func (x *PointerPosition) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PointerPosition) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type EventPointerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata         *EventMetadata     `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PointerPositions []*PointerPosition `protobuf:"bytes,5,rep,name=pointer_positions,json=pointerPositions,proto3" json:"pointer_positions,omitempty"`
}

func (x *EventPointerUpdate) Reset() {
	*x = EventPointerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_pointer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventPointerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPointerUpdate) ProtoMessage() {}

func (x *EventPointerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_pointer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPointerUpdate.ProtoReflect.Descriptor instead.
func (*EventPointerUpdate) Descriptor() ([]byte, []int) {
	return file_proto_model_pointer_proto_rawDescGZIP(), []int{1}
}

func (x *EventPointerUpdate) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EventPointerUpdate) GetPointerPositions() []*PointerPosition {
	if x != nil {
		return x.PointerPositions
	}
	return nil
}

// Send pointer movements to the server
type UpdatePointerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoardId          *UUID              `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	PointerPositions []*PointerPosition `protobuf:"bytes,2,rep,name=pointer_positions,json=pointerPositions,proto3" json:"pointer_positions,omitempty"`
}

func (x *UpdatePointerRequest) Reset() {
	*x = UpdatePointerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_pointer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePointerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointerRequest) ProtoMessage() {}

func (x *UpdatePointerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_pointer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePointerRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_pointer_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePointerRequest) GetBoardId() *UUID {
	if x != nil {
		return x.BoardId
	}
	return nil
}

func (x *UpdatePointerRequest) GetPointerPositions() []*PointerPosition {
	if x != nil {
		return x.PointerPositions
	}
	return nil
}

type UpdatePointerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdatePointerResponse) Reset() {
	*x = UpdatePointerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_pointer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePointerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePointerResponse) ProtoMessage() {}

func (x *UpdatePointerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_pointer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePointerResponse.ProtoReflect.Descriptor instead.
func (*UpdatePointerResponse) Descriptor() ([]byte, []int) {
	return file_proto_model_pointer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePointerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_model_pointer_proto protoreflect.FileDescriptor

var file_proto_model_pointer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0f,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x12,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x43, 0x0a, 0x11, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x14, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x52, 0x07, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x11, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x31, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x61, 0x6e, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6e, 0x2f, 0x64, 0x72, 0x61, 0x77, 0x2d,
	0x74, 0x6f, 0x67, 0x65, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_pointer_proto_rawDescOnce sync.Once
	file_proto_model_pointer_proto_rawDescData = file_proto_model_pointer_proto_rawDesc
)

func file_proto_model_pointer_proto_rawDescGZIP() []byte {
	file_proto_model_pointer_proto_rawDescOnce.Do(func() {
		file_proto_model_pointer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_pointer_proto_rawDescData)
	})
	return file_proto_model_pointer_proto_rawDescData
}

var file_proto_model_pointer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_model_pointer_proto_goTypes = []interface{}{
	(*PointerPosition)(nil),       // 0: model.PointerPosition
	(*EventPointerUpdate)(nil),    // 1: model.EventPointerUpdate
	(*UpdatePointerRequest)(nil),  // 2: model.UpdatePointerRequest
	(*UpdatePointerResponse)(nil), // 3: model.UpdatePointerResponse
	(*EventMetadata)(nil),         // 4: model.EventMetadata
	(*UUID)(nil),                  // 5: model.UUID
}
var file_proto_model_pointer_proto_depIdxs = []int32{
	4, // 0: model.EventPointerUpdate.metadata:type_name -> model.EventMetadata
	0, // 1: model.EventPointerUpdate.pointer_positions:type_name -> model.PointerPosition
	5, // 2: model.UpdatePointerRequest.board_id:type_name -> model.UUID
	0, // 3: model.UpdatePointerRequest.pointer_positions:type_name -> model.PointerPosition
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_model_pointer_proto_init() }
func file_proto_model_pointer_proto_init() {
	if File_proto_model_pointer_proto != nil {
		return
	}
	file_proto_model_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_model_pointer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointerPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_pointer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventPointerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_pointer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePointerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_pointer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePointerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_pointer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_pointer_proto_goTypes,
		DependencyIndexes: file_proto_model_pointer_proto_depIdxs,
		MessageInfos:      file_proto_model_pointer_proto_msgTypes,
	}.Build()
	File_proto_model_pointer_proto = out.File
	file_proto_model_pointer_proto_rawDesc = nil
	file_proto_model_pointer_proto_goTypes = nil
	file_proto_model_pointer_proto_depIdxs = nil
}
