// @generated by protobuf-ts 2.9.4 with parameter ts_nocheck
// @generated from protobuf file "proto/service.proto" (package "service", syntax proto3)
// tslint:disable
// @ts-nocheck
import { UpdatePointerResponse } from "./model/pointer";
import { UpdatePointerRequest } from "./model/pointer";
import { GetBoardMessagesResponse } from "./model/chat";
import { GetBoardMessagesRequest } from "./model/chat";
import { ChatMessageResponse } from "./model/chat";
import { ChatMessageRequest } from "./model/chat";
import { DrawingDetectResponse } from "./model/drawing";
import { GetBoardDrawingsResponse } from "./model/drawing";
import { GetBoardDrawingsRequest } from "./model/drawing";
import { UpdateDrawingResponse } from "./model/drawing";
import { UpdateDrawingRequest } from "./model/drawing";
import { GetBoardRequest } from "./model/board";
import { GetBoardResponse } from "./model/board";
import { CreateBoardRequest } from "./model/board";
import { GetUserResponse } from "./model/user";
import { Empty } from "../google/protobuf/empty";
import { CreateUserResponse } from "./model/user";
import { CreateUserRequest } from "./model/user";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service service.UserService
 */
export const UserService = new ServiceType("service.UserService", [
    { name: "CreateUser", options: {}, I: CreateUserRequest, O: CreateUserResponse },
    { name: "GetUser", options: {}, I: Empty, O: GetUserResponse },
    { name: "DeleteUser", options: {}, I: Empty, O: GetUserResponse }
]);
/**
 * @generated ServiceType for protobuf service service.BoardService
 */
export const BoardService = new ServiceType("service.BoardService", [
    { name: "CreateBoard", options: {}, I: CreateBoardRequest, O: GetBoardResponse },
    { name: "GetBoard", options: {}, I: GetBoardRequest, O: GetBoardResponse },
    { name: "DeleteBoard", options: {}, I: GetBoardRequest, O: GetBoardResponse },
    { name: "UpdateDrawing", options: {}, I: UpdateDrawingRequest, O: UpdateDrawingResponse },
    { name: "GetBoardDrawings", options: {}, I: GetBoardDrawingsRequest, O: GetBoardDrawingsResponse },
    { name: "DrawingDetect", options: {}, I: GetBoardDrawingsRequest, O: DrawingDetectResponse }
]);
/**
 * @generated ServiceType for protobuf service service.ChatService
 */
export const ChatService = new ServiceType("service.ChatService", [
    { name: "SendMessage", options: {}, I: ChatMessageRequest, O: ChatMessageResponse },
    { name: "GetBoardMessages", options: {}, I: GetBoardMessagesRequest, O: GetBoardMessagesResponse }
]);
/**
 * @generated ServiceType for protobuf service service.PointerService
 */
export const PointerService = new ServiceType("service.PointerService", [
    { name: "UpdatePointer", options: {}, I: UpdatePointerRequest, O: UpdatePointerResponse }
]);
